# Air configuration file
# Docs: https://github.com/air-verse/air

[build]
  # Command to build your app
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  # Binary to run
  bin = "./tmp/main"
  # Watch these directories for changes
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "bin"]
  exclude_file = []
  # Delay before restart (ms)
  delay = 1000
  # Send interrupt signal, then kill after timeout (ms)
  kill_delay = 500

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[debug]
  enable = false 